version = 0.1

[default.deploy.parameters]
stack_name = "sav"
resolve_s3 = true
s3_prefix = "sav"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "GoogleClientId=\"86732526103-dchhms8v8od6qa97ktlluf1b5173hqvl.apps.googleusercontent.com\" AdminEmail=\"kaihedrick@icloud.com\" AppBaseUrl=\"http://localhost:5173\""
image_repositories = []

[default.global.parameters]
region = "us-west-2"
